# Generated by Django 6.0.4 on 2026-04-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MergeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_filename', models.CharField(max_length=255)),
                ('input_files', models.TextField()),
                ('total_pages', models.PositiveIntegerField()),
                ('file_size_kb', models.FloatField()),
                ('output_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
