# Generated by Django 6.0.4 on 2026-04-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(choices=[('merge', 'Merge'), ('split', 'Split'), ('extract', 'Extract Pages'), ('rotate', 'Rotate'), ('compress', 'Compress')], max_length=20)),
                ('output_filename', models.CharField(max_length=255)),
                ('input_files', models.TextField()),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('file_size_kb', models.FloatField(default=0)),
                ('output_path', models.CharField(max_length=500)),
                ('extra_info', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='MergeJob',
        ),
    ]
